name: Deploy gmaps-ui to GH Pages

on:
  push:
    branches: [ master ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: gmaps-ui/package-lock.json

      - name: Install deps
        working-directory: gmaps-ui
        run: npm ci

      - name: Build (ghpages)
        working-directory: gmaps-ui
        run: npx ng build --configuration=ghpages
      - name: SPA 404 fallback
        working-directory: gmaps-ui
        run: cp dist/gmaps-ui/browser/index.html dist/gmaps-ui/browser/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: gmaps-ui/dist/gmaps-ui/browser

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
